# Site settings
title: Antton Alberdi's site
brand: AnttonAlberdi
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://anttonalberdi.github.io/"
copyright: Antton Alberdi CC-by 2019

# Build settings
markdown: kramdown

# The video that plays.
video: "u7deClndzQw"

# The navigation.
navigation:
  left:
    links:
      - title: CV
        href: /cv/
      - title: Publications
        href: /publications/
      - title: Resources
        dropdown:
          - title: SubMenu 1
            href: #
          - title: SubMenu 2
            href: #
          - title: SubMenu 3
            href: #
  right:
    content: nav/right.html

# The footer section.
footer:
  sections:
    - title: Research Social
      links:
        - href: https://orcid.org/0000-0002-2875-6446
          title: ORCID
        - href: https://www.researchgate.net/profile/Antton_Alberdi
          title: ResearchGate
        - href: https://publons.com/researcher/1301567/antton-alberdi/
          title: Publons
    - title: Useful Links 2
      links:
        - href: https://www.google.com
          title: Google.com
        - href: https://www.yahoo.com
          title: Yahoo.com
        - href: https://www.msn.com
          title: MSN
    - title: Useful Links 3
      links:
        - href: https://www.google.com
          title: Google.com
        - href: https://www.yahoo.com
          title: Yahoo.com
        - href: https://www.msn.com
          title: MSN
  company_info:
    title: Our office
    name: Company Name
    website: http://companysite.com
    phone: 555-123-4567
    address:
      street: 123 Main St.
      city: Dallas
      state: TX
      zip: 75001
